# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import algo


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.csv_ip_label = QtWidgets.QLabel(self.centralwidget)
        self.csv_ip_label.setGeometry(QtCore.QRect(140, 140, 91, 17))
        self.csv_ip_label.setObjectName("csv_ip_label")

        self.csv_ip_line = QtWidgets.QLineEdit(self.centralwidget)
        self.csv_ip_line.setGeometry(QtCore.QRect(310, 130, 351, 25))
        self.csv_ip_line.setObjectName("csv_ip_line")
        self.csv_ip_line.setPlaceholderText("file path of csv file")

        self.img_dir_label = QtWidgets.QLabel(self.centralwidget)
        self.img_dir_label.setGeometry(QtCore.QRect(140, 200, 71, 17))
        self.img_dir_label.setObjectName("img_dir_label")

        self.img_dir_line = QtWidgets.QLineEdit(self.centralwidget)
        self.img_dir_line.setGeometry(QtCore.QRect(310, 190, 351, 25))
        self.img_dir_line.setObjectName("img_dir_line")
        self.img_dir_line.setPlaceholderText(
            "directory path containing images")

        self.kml_ip_label = QtWidgets.QLabel(self.centralwidget)
        self.kml_ip_label.setGeometry(QtCore.QRect(140, 250, 67, 17))
        self.kml_ip_label.setObjectName("kml_ip_label")

        self.kml_ip_line = QtWidgets.QLineEdit(self.centralwidget)
        self.kml_ip_line.setGeometry(QtCore.QRect(310, 240, 351, 25))
        self.kml_ip_line.setObjectName("kml_ip_line")
        self.kml_ip_line.setPlaceholderText("file path of kml file")

        self.c1_label = QtWidgets.QLabel(self.centralwidget)
        self.c1_label.setGeometry(QtCore.QRect(140, 310, 111, 17))
        self.c1_label.setObjectName("c1_label")

        self.c1_lat_line = QtWidgets.QLineEdit(self.centralwidget)
        self.c1_lat_line.setGeometry(QtCore.QRect(310, 300, 161, 25))
        self.c1_lat_line.setText("")
        self.c1_lat_line.setObjectName("c1_lat_line")
        self.c1_lat_line.setPlaceholderText("lat")

        self.c1_lon_line = QtWidgets.QLineEdit(self.centralwidget)
        self.c1_lon_line.setGeometry(QtCore.QRect(510, 300, 151, 25))
        self.c1_lon_line.setText("")
        self.c1_lon_line.setObjectName("c1_lon_line")
        self.c1_lon_line.setPlaceholderText("lon")

        self.c2_label = QtWidgets.QLabel(self.centralwidget)
        self.c2_label.setGeometry(QtCore.QRect(140, 360, 91, 17))
        self.c2_label.setObjectName("c2_label")

        self.c2_lat_line = QtWidgets.QLineEdit(self.centralwidget)
        self.c2_lat_line.setGeometry(QtCore.QRect(310, 360, 161, 25))
        self.c2_lat_line.setObjectName("c2_lat_line")
        self.c2_lat_line.setPlaceholderText("lat")

        self.c2_lon_line = QtWidgets.QLineEdit(self.centralwidget)
        self.c2_lon_line.setGeometry(QtCore.QRect(512, 360, 151, 25))
        self.c2_lon_line.setObjectName("c2_lon_line")
        self.c2_lon_line.setPlaceholderText("lon")

        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(380, 430, 171, 71))
        self.submit_button.setObjectName("submit_button")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.submit_button.clicked.connect(self.submit_clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.csv_ip_label.setText(_translate("MainWindow", "CSV input"))
        self.img_dir_label.setText(_translate("MainWindow", "IMG directory"))
        self.kml_ip_label.setText(_translate("MainWindow", "kML input"))
        self.c1_label.setText(_translate("MainWindow", "Co-ordinate 1"))
        self.c2_label.setText(_translate("MainWindow", "Co-ordinate 2"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))

        self.csv_ip_label.adjustSize()
        self.img_dir_label.adjustSize()
        self.kml_ip_label.adjustSize()
        self.c1_label.adjustSize()
        self.c2_label.adjustSize()
        # self.submit_button.adjustSize()

    def get_csv_file(self):
        self.csv_file = self.csv_ip_line.text()
        return self.csv_ip_line.text()

    def get_img_dir(self):
        self.img_dir = self.img_dir_line.text()
        return self.img_dir_line.text()

    def get_kml_ip(self):
        self.kml_ip = self.kml_ip_line.text()
        return self.kml_ip_line.text()

    def get_c1_lat(self):
        self.c1_lat = self.c1_lat_line.text()
        return self.c1_lat_line.text()

    def get_c1_lon(self):
        self.c1_lon = self.c1_lon_line.text()
        return self.c1_lon_line.text()

    def get_c2_lat(self):
        self.c2_lat = self.c2_lat_line.text()
        return self.c2_lat_line.text()

    def get_c2_lon(self):
        self.c2_lon = self.c2_lon_line.text()
        return self.c2_lon_line.text()

    def clear_all_fields(self):
        self.csv_ip_line.setText("")
        self.img_dir_line.setText("")
        self.kml_ip_line.setText("")
        self.c1_lat_line.setText("")
        self.c1_lon_line.setText("")
        self.c2_lat_line.setText("")
        self.c2_lon_line.setText("")

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("One of the input field is empty.")
        msg.setIcon(QMessageBox.Critical)
        msg.exec_()

    def submit_clicked(self):
       

        if(self.get_csv_file() == ""
           or self.get_img_dir() == ""
           or self.get_c1_lat() == ""
           or self.get_c1_lon() == ""
           or self.get_c2_lat() == ""
           or self.get_c2_lon() == ""
           ):
            self.show_popup()
        else:
            print("csv file  : "+self.get_csv_file())
            print("image dir : "+self.get_img_dir())
            print("kml file  : "+self.get_kml_ip())
            print("c1-> lat  : "+self.get_c1_lat())
            print("c1-> lon  : "+self.get_c1_lon())
            print("c2-> lat  : "+self.get_c2_lat())
            print("c2-> lon  : "+self.get_c2_lon())
            print("------------------------------")

            obj1 = algo.Isolate_img(
                self.get_csv_file(),
                self.get_img_dir(),
                self.get_c1_lat(),
                self.get_c1_lon(),
                self.get_c2_lat(),
                self.get_c2_lon()
            )

            del obj1
            self.clear_all_fields()



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
